### ISSUE TITLE
4Seasons Dataset Code

### ISSUE THREAD

**Issue by muzi-Lu** [sijieaaa/RobustLoc#2]
Hello，this is an excellent work in camera localization!
I want to run this code in 4Seasons Dataset like you do, but it does not have the matching code, did I miss important code or could you provide the relevant code？
Thanks!

**Comment by sijieaaa** [comment]
Hi,

We are preparing the code for 4seasons, and it would be released at the end of this month or early next month.

Thanks.

**Comment by muzi-Lu** [comment]
Thanks again!
